# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller specification file for Blinter.

This spec file includes optimizations to reduce antivirus false positives:
- Version information resource for legitimacy
- Disabled UPX compression (--noupx) which triggers heuristic detection
- Console application metadata
- Company and product information
"""

import sys
from pathlib import Path

block_cipher = None

# Version information to embed in the executable
# This makes the executable appear more legitimate to antivirus software
version_info = {
    'version': '1.0.0.0',  # Will be overridden by build script with actual version
    'company_name': 'tboy1337',
    'file_description': 'Blinter - Professional Batch File Linter for Windows',
    'internal_name': 'Blinter',
    'legal_copyright': '© 2025 tboy1337. Licensed under AGPL-3.0.',
    'original_filename': 'Blinter.exe',
    'product_name': 'Blinter',
    'product_version': '1.0.0.0',  # Will be overridden by build script
}

a = Analysis(
    ['blinter.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('py.typed', '.'),  # Include type marker file
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Blinter',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,  # CRITICAL: Disable UPX compression to reduce AV false positives
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,  # Console application
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version='file_version_info.txt',  # Will be generated by build script
    icon='resources/blinter_icon.ico',
)
